apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: amq
    spec:
      restartPolicy: Always
      containers:
        - name: amq
          image: rabbitmq:3-management
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"
          ports:
            - containerPort: 5672
              protocol: TCP
                    readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: amq
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: amq
                  key: password
