apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: us.gcr.io/your-project-name/api:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              cpu: "300m"
              memory: "500Mi"
          # You'd need to create a http endpoint GET /_healthcheck for the heathcheck
          readinessProbe:
            httpGet:
              path: /_healthcheck
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /_healthcheck
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 15
          env:
            - name: AMQ_ENV_RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: amq
                  key: user
            - name: AMQ_ENV_RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: amq
                  key: password
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: NODE_ENV
